"""opd consultations, prescriptions, prescription items

Revision ID: b68b48e2eaee
Revises: 86dc01c79838
Create Date: 2026-07-19 10:49:33.651855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68b48e2eaee'
down_revision: Union[str, Sequence[str], None] = '86dc01c79838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opd_consultations',
    sa.Column('consult_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('chief_complaint', sa.String(length=500), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=20), nullable=True),
    sa.Column('diagnosis_text', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('consult_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('consult_id')
    )
    op.create_index(op.f('ix_opd_consultations_doctor_id'), 'opd_consultations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_opd_consultations_patient_id'), 'opd_consultations', ['patient_id'], unique=False)
    op.create_table('opd_prescriptions',
    sa.Column('rx_id', sa.Integer(), nullable=False),
    sa.Column('consult_id', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consult_id'], ['opd_consultations.consult_id'], ),
    sa.PrimaryKeyConstraint('rx_id')
    )
    op.create_index(op.f('ix_opd_prescriptions_consult_id'), 'opd_prescriptions', ['consult_id'], unique=True)
    op.create_table('opd_prescription_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('rx_id', sa.Integer(), nullable=False),
    sa.Column('med_name', sa.String(length=255), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['rx_id'], ['opd_prescriptions.rx_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_opd_prescription_items_rx_id'), 'opd_prescription_items', ['rx_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opd_prescription_items_rx_id'), table_name='opd_prescription_items')
    op.drop_table('opd_prescription_items')
    op.drop_index(op.f('ix_opd_prescriptions_consult_id'), table_name='opd_prescriptions')
    op.drop_table('opd_prescriptions')
    op.drop_index(op.f('ix_opd_consultations_patient_id'), table_name='opd_consultations')
    op.drop_index(op.f('ix_opd_consultations_doctor_id'), table_name='opd_consultations')
    op.drop_table('opd_consultations')
    # ### end Alembic commands ###
