"""opd visits diagnoses prescriptions

Revision ID: 2587a49be27b
Revises: 86dc01c79838
Create Date: 2026-07-16 17:32:17.439357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2587a49be27b'
down_revision: Union[str, Sequence[str], None] = '86dc01c79838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opd_visits',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'completed', name='opd_visit_status', native_enum=False), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_index(op.f('ix_opd_visits_doctor_id'), 'opd_visits', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_opd_visits_patient_id'), 'opd_visits', ['patient_id'], unique=False)
    op.create_table('opd_diagnoses',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['opd_visits.visit_id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_index(op.f('ix_opd_diagnoses_visit_id'), 'opd_diagnoses', ['visit_id'], unique=False)
    op.create_table('opd_prescriptions',
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['opd_visits.visit_id'], ),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_index(op.f('ix_opd_prescriptions_visit_id'), 'opd_prescriptions', ['visit_id'], unique=False)
    op.create_table('opd_prescription_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['opd_prescriptions.prescription_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_opd_prescription_items_prescription_id'), 'opd_prescription_items', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opd_prescription_items_prescription_id'), table_name='opd_prescription_items')
    op.drop_table('opd_prescription_items')
    op.drop_index(op.f('ix_opd_prescriptions_visit_id'), table_name='opd_prescriptions')
    op.drop_table('opd_prescriptions')
    op.drop_index(op.f('ix_opd_diagnoses_visit_id'), table_name='opd_diagnoses')
    op.drop_table('opd_diagnoses')
    op.drop_index(op.f('ix_opd_visits_patient_id'), table_name='opd_visits')
    op.drop_index(op.f('ix_opd_visits_doctor_id'), table_name='opd_visits')
    op.drop_table('opd_visits')
    # ### end Alembic commands ###
