"""ipd wards beds admissions vitals

Revision ID: c97d5e10b49a
Revises: 4b1f7c9a2d63
Create Date: 2026-07-21 20:50:09.555264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97d5e10b49a'
down_revision: Union[str, Sequence[str], None] = '4b1f7c9a2d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipd_wards',
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ward_type', sa.Enum('general', 'icu', 'private', 'semi_private', name='ipd_ward_type', native_enum=False), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ward_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ipd_beds',
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('vacant', 'occupied', 'maintenance', name='ipd_bed_status', native_enum=False), server_default='vacant', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['ipd_wards.ward_id'], ),
    sa.PrimaryKeyConstraint('bed_id')
    )
    op.create_index(op.f('ix_ipd_beds_ward_id'), 'ipd_beds', ['ward_id'], unique=False)
    op.create_table('ipd_admissions',
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('consult_id', sa.Integer(), nullable=True),
    sa.Column('admitting_doctor_id', sa.Integer(), nullable=False),
    sa.Column('admission_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('admitted', 'discharged', name='ipd_admission_status', native_enum=False), server_default='admitted', nullable=False),
    sa.Column('admitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('discharged_at', sa.DateTime(), nullable=True),
    sa.Column('discharge_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admitting_doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['consult_id'], ['opd_consultations.consult_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('admission_id')
    )
    op.create_index(op.f('ix_ipd_admissions_admitting_doctor_id'), 'ipd_admissions', ['admitting_doctor_id'], unique=False)
    op.create_index(op.f('ix_ipd_admissions_consult_id'), 'ipd_admissions', ['consult_id'], unique=False)
    op.create_index(op.f('ix_ipd_admissions_patient_id'), 'ipd_admissions', ['patient_id'], unique=False)
    op.create_table('ipd_bed_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['ipd_admissions.admission_id'], ),
    sa.ForeignKeyConstraint(['bed_id'], ['ipd_beds.bed_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_ipd_bed_assignments_admission_id'), 'ipd_bed_assignments', ['admission_id'], unique=False)
    op.create_index(op.f('ix_ipd_bed_assignments_bed_id'), 'ipd_bed_assignments', ['bed_id'], unique=False)
    op.create_table('ipd_vitals_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('temperature_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('pulse_bpm', sa.Integer(), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('spo2_percent', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['ipd_admissions.admission_id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_ipd_vitals_records_admission_id'), 'ipd_vitals_records', ['admission_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed an op.alter_column('users', 'role', ...)
    # here - a cosmetic type-comparison artifact of a prior migration
    # (Enum(native_enum=False) vs. plain VARCHAR both produce the same
    # underlying column), unrelated to IPD. Deliberately dropped from this
    # migration to keep it scoped to IPD's own tables only.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipd_vitals_records_admission_id'), table_name='ipd_vitals_records')
    op.drop_table('ipd_vitals_records')
    op.drop_index(op.f('ix_ipd_bed_assignments_bed_id'), table_name='ipd_bed_assignments')
    op.drop_index(op.f('ix_ipd_bed_assignments_admission_id'), table_name='ipd_bed_assignments')
    op.drop_table('ipd_bed_assignments')
    op.drop_index(op.f('ix_ipd_admissions_patient_id'), table_name='ipd_admissions')
    op.drop_index(op.f('ix_ipd_admissions_consult_id'), table_name='ipd_admissions')
    op.drop_index(op.f('ix_ipd_admissions_admitting_doctor_id'), table_name='ipd_admissions')
    op.drop_table('ipd_admissions')
    op.drop_index(op.f('ix_ipd_beds_ward_id'), table_name='ipd_beds')
    op.drop_table('ipd_beds')
    op.drop_table('ipd_wards')
    # ### end Alembic commands ###
