"""billing line items and payments

Revision ID: 094edb9a848a
Revises: 42acc746567a
Create Date: 2026-07-20 15:27:52.856081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094edb9a848a'
down_revision: Union[str, Sequence[str], None] = '42acc746567a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_bill_items_bill_id'), 'bill_items', ['bill_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mode', sa.Enum('cash', 'upi', 'card', 'other', name='payment_mode', native_enum=False), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_bill_id'), 'payments', ['bill_id'], unique=False)
    op.add_column('bills', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('bills', sa.Column('finalized_at', sa.DateTime(), nullable=True))
    # Named explicitly (autogenerate left this None, which downgrade() can't
    # use - drop_constraint needs a real name, and no naming_convention is
    # configured on this project's MetaData to derive one automatically).
    op.create_foreign_key(
        'fk_bills_created_by_users', 'bills', 'users', ['created_by'], ['user_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bills_created_by_users', 'bills', type_='foreignkey')
    op.drop_column('bills', 'finalized_at')
    op.drop_column('bills', 'created_by')
    op.drop_index(op.f('ix_payments_bill_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_bill_items_bill_id'), table_name='bill_items')
    op.drop_table('bill_items')
    # ### end Alembic commands ###
