"""pharmacy medicines batches dispenses

Revision ID: 92bd798e6f63
Revises: bb794afc5707
Create Date: 2026-07-19 13:29:49.979050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bd798e6f63'
down_revision: Union[str, Sequence[str], None] = 'bb794afc5707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_medicines',
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('reorder_level', sa.Integer(), server_default='10', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('medicine_id')
    )
    op.create_table('pharmacy_medicine_batches',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['pharmacy_medicines.medicine_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_pharmacy_medicine_batches_expiry_date'), 'pharmacy_medicine_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_pharmacy_medicine_batches_medicine_id'), 'pharmacy_medicine_batches', ['medicine_id'], unique=False)
    op.create_table('pharmacy_dispenses',
    sa.Column('dispense_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('dispensed_by', sa.Integer(), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['opd_prescriptions.rx_id'], ),
    sa.PrimaryKeyConstraint('dispense_id')
    )
    op.create_index(op.f('ix_pharmacy_dispenses_dispensed_by'), 'pharmacy_dispenses', ['dispensed_by'], unique=False)
    op.create_index(op.f('ix_pharmacy_dispenses_patient_id'), 'pharmacy_dispenses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_dispenses_prescription_id'), 'pharmacy_dispenses', ['prescription_id'], unique=False)
    op.create_table('pharmacy_dispense_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('dispense_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispense_id'], ['pharmacy_dispenses.dispense_id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['pharmacy_medicines.medicine_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_pharmacy_dispense_items_dispense_id'), 'pharmacy_dispense_items', ['dispense_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_dispense_items_medicine_id'), 'pharmacy_dispense_items', ['medicine_id'], unique=False)
    op.create_table('pharmacy_dispense_item_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispense_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity_deducted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['pharmacy_medicine_batches.batch_id'], ),
    sa.ForeignKeyConstraint(['dispense_item_id'], ['pharmacy_dispense_items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_dispense_item_batches_batch_id'), 'pharmacy_dispense_item_batches', ['batch_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_dispense_item_batches_dispense_item_id'), 'pharmacy_dispense_item_batches', ['dispense_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_dispense_item_batches_dispense_item_id'), table_name='pharmacy_dispense_item_batches')
    op.drop_index(op.f('ix_pharmacy_dispense_item_batches_batch_id'), table_name='pharmacy_dispense_item_batches')
    op.drop_table('pharmacy_dispense_item_batches')
    op.drop_index(op.f('ix_pharmacy_dispense_items_medicine_id'), table_name='pharmacy_dispense_items')
    op.drop_index(op.f('ix_pharmacy_dispense_items_dispense_id'), table_name='pharmacy_dispense_items')
    op.drop_table('pharmacy_dispense_items')
    op.drop_index(op.f('ix_pharmacy_dispenses_prescription_id'), table_name='pharmacy_dispenses')
    op.drop_index(op.f('ix_pharmacy_dispenses_patient_id'), table_name='pharmacy_dispenses')
    op.drop_index(op.f('ix_pharmacy_dispenses_dispensed_by'), table_name='pharmacy_dispenses')
    op.drop_table('pharmacy_dispenses')
    op.drop_index(op.f('ix_pharmacy_medicine_batches_medicine_id'), table_name='pharmacy_medicine_batches')
    op.drop_index(op.f('ix_pharmacy_medicine_batches_expiry_date'), table_name='pharmacy_medicine_batches')
    op.drop_table('pharmacy_medicine_batches')
    op.drop_table('pharmacy_medicines')
    # ### end Alembic commands ###
