"""lab test catalog

Revision ID: bb794afc5707
Revises: 7711a41c4a08
Create Date: 2026-07-19 13:04:21.802846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb794afc5707'
down_revision: Union[str, Sequence[str], None] = '7711a41c4a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_test_catalog',
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('loinc_code', sa.String(length=20), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('default_reference_range', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('catalog_id')
    )
    op.create_index(op.f('ix_lab_test_catalog_loinc_code'), 'lab_test_catalog', ['loinc_code'], unique=True)
    op.add_column('lab_orders', sa.Column('catalog_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lab_orders_catalog_id'), 'lab_orders', ['catalog_id'], unique=False)
    # Named explicitly (autogenerate left this None, which downgrade() can't
    # use - drop_constraint needs a real name, and no naming_convention is
    # configured on this project's MetaData to derive one automatically).
    op.create_foreign_key(
        'fk_lab_orders_catalog_id_lab_test_catalog',
        'lab_orders', 'lab_test_catalog', ['catalog_id'], ['catalog_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lab_orders_catalog_id_lab_test_catalog', 'lab_orders', type_='foreignkey')
    op.drop_index(op.f('ix_lab_orders_catalog_id'), table_name='lab_orders')
    op.drop_column('lab_orders', 'catalog_id')
    op.drop_index(op.f('ix_lab_test_catalog_loinc_code'), table_name='lab_test_catalog')
    op.drop_table('lab_test_catalog')
    # ### end Alembic commands ###
