"""link users to patient records for portal access

Revision ID: 6e2e39f6abc7
Revises: 094edb9a848a
Create Date: 2026-07-20 20:40:22.853921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2e39f6abc7'
down_revision: Union[str, Sequence[str], None] = '094edb9a848a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_patient_id'), 'users', ['patient_id'], unique=False)
    # Named explicitly (autogenerate left this None, which downgrade() can't
    # use - drop_constraint needs a real name, and no naming_convention is
    # configured on this project's MetaData to derive one automatically).
    op.create_foreign_key(
        'fk_users_patient_id_patients', 'users', 'patients', ['patient_id'], ['patient_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_patient_id_patients', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_patient_id'), table_name='users')
    op.drop_column('users', 'patient_id')
    # ### end Alembic commands ###
